/**
  ******************************************************************************
  * @file    motor_app.c
  * @brief   Application layer: test AK80-9
  ******************************************************************************
  */
#include "motor_app.h"
#include "main.h"       /* HAL, system clock etc. */
#include "fdcan_drv.h"
#include "ak80_9.h"

/* FDCAN1 handle generated by CubeMX */
extern FDCAN_HandleTypeDef hfdcan1;

#define TEST_MOTOR_ID     1          /* test motor ID */
#define TEST_CTRL_PERIOD  10         /* control period ms */

static uint32_t s_last_tick = 0;
static uint8_t  s_inited = 0;

void motor_app_init(void)
{
    /* 1. init universal FDCAN bus (configure filters and start) */
    fdcan_drv_init(&hfdcan1);

    /* 2. init AK80-9 driver (register rx callback) */
    ak80_9_init(&hfdcan1);

    /* 3. enable motor to MIT run state */
    ak80_9_enable(&hfdcan1, TEST_MOTOR_ID);

    s_inited = 1;
}

void motor_app_run(void)
{
    uint32_t now = HAL_GetTick();

    if (s_inited == 0) { return; }

    /* send control command periodically */
    if ((now - s_last_tick) >= TEST_CTRL_PERIOD)
    {
        s_last_tick = now;

        /* slow constant-speed rotation (velocity mode):
         *   p_des=0.0  (unused since Kp=0)
         *   v_des=1.0 rad/s -> constant slow rotation
         *   Kp  =0.0       -> don't hold a position, allow continuous rotation
         *   Kd  =2.0       -> velocity damping, keeps speed stable
         *   t_ff=0.0       -> no feed-forward */
        ak80_9_set_control(&hfdcan1, TEST_MOTOR_ID,
                           0.0f, 1.0f, 0.0f, 2.0f, 0.0f);
    }
}