/**
  ******************************************************************************
  * @file    motor_app.c
  * @brief   Application layer: test AK80-9
  ******************************************************************************
  */
#include "motor_app.h"
#include "main.h"       /* HAL, system clock etc. */
#include "fdcan_drv.h"
#include "ak80_9.h"

/* FDCAN1 handle generated by CubeMX */
extern FDCAN_HandleTypeDef hfdcan1;

#define TEST_MOTOR_ID     1          /* test motor ID */
#define TEST_CTRL_PERIOD  10         /* control period ms */

static uint32_t s_last_tick = 0;
static uint8_t  s_inited = 0;

/* Simple RX diagnostic:
 * Watch 'g_rx_fifo_level' in Keil. If it stays 0, the feedback frame never
 * reached the FDCAN RX FIFO0 (physical-layer issue). */
volatile uint32_t g_rx_fifo_level = 0;

void motor_app_init(void)
{
    /* 1. init universal FDCAN bus (configure filters and start) */
    fdcan_drv_init(&hfdcan1);

    /* 2. init AK80-9 driver (register rx callback) */
    ak80_9_init(&hfdcan1);

    /* 3. enable motor to MIT run state */
    ak80_9_enable(&hfdcan1, TEST_MOTOR_ID);

    s_inited = 1;
}

void motor_app_run(void)
{
    uint32_t now = HAL_GetTick();

    if (s_inited == 0) { return; }

    /* send control command periodically */
    if ((now - s_last_tick) >= TEST_CTRL_PERIOD)
    {
        s_last_tick = now;

        /* command values: slow constant-speed rotation (velocity mode) */
        const float cmd_pos = 0.0f;  /* unused since Kp=0 */
        const float cmd_vel = 1.0f;  /* target speed rad/s */
        const float cmd_kp  = 0.0f;  /* don't hold a position */
        const float cmd_kd  = 2.0f;  /* velocity damping */
        const float cmd_tq  = 0.0f;  /* no feed-forward */

        ak80_9_set_control(&hfdcan1, TEST_MOTOR_ID,
                           cmd_pos, cmd_vel, cmd_kp, cmd_kd, cmd_tq);
    }

    /* RX diagnostic: poll FIFO0 fill level (no interrupt needed).
     * Motor feedback is visible directly in 'ak80_9_state[0]'. */
    g_rx_fifo_level = HAL_FDCAN_GetRxFifoFillLevel(&hfdcan1, FDCAN_RX_FIFO0);
}